<li @if(Request::segment(3) == 'agency' && Request::segment(4) == 'details') class="active" @endif><a href="{{SITE_LANG}}/account/agency/details"><i class="glyph-icon flaticon-user-1"></i><span>{{ trans('common.AgencyDetails') }}</span></a></li>
<li @if((Request::segment(3) == 'agency' && Request::segment(4) == 'properties') || in_array(Request::segment(3),['plans','submit'])) class="active" @endif><a href="{{SITE_LANG}}/account/agency/properties"><i class="glyph-icon flaticon-buildings-1"></i><span>{{ trans('common.AgencyProperties') }}</span></a></li>
<li @if(Request::segment(3) == 'agency' && in_array(Request::segment(4),['agents','agent'])) class="active" @endif><a href="{{SITE_LANG}}/account/agency/agents"><i class="glyph-icon flaticon-user"></i><span>{{ trans('common.Realestateemployees') }}</span></a></li>
<li @if(Request::segment(3) == 'agency' && Request::segment(4) == "messages") class="active" @endif><a href="{{SITE_LANG}}/account/agency/messages"><i class="glyph-icon flaticon-multimedia"></i><span>{{ trans('common.AgencyMessages') }}</span>@if(Auth::user()->agency->getUnreadMessages())<sup class="msg-notification"><b>{{ Auth::user()->agency->getUnreadMessages()->count() }}</b></sup>@endif</a></li>
<li @if(Request::segment(3) == 'agency' && Request::segment(4) == 'subscription') class="active" @endif><a href="{{SITE_LANG}}/account/agency/subscription"><i class="glyph-icon flaticon-trophy" aria-hidden="true"></i><span>{{ trans('common.SubscriptionPlan') }}</span></a></li>
<li @if(Request::segment(3) == 'agency' && Request::segment(4) == 'apicredential') class="active" @endif><a href="{{SITE_LANG}}/account/agency/apicredential"><i class="glyph-icon flaticon-tool" aria-hidden="true"></i><span>{{ trans('common.Api') }}</span></a></li>
<li @if(Request::segment(3) == 'agency' && Request::segment(4) == 'synchronization') class="active" @endif><a href="{{SITE_LANG}}/account/agency/synchronization"><i class="glyph-icon flaticon-progress-arrows" aria-hidden="true"></i><span>{{ trans('common.Synchronization') }}</span></a></li>
@if(Auth::user()->package_id >= 2)
  <li @if(Request::segment(3) == 'agency' && Request::segment(4) == 'statistics') class="active" @endif><a href="{{SITE_LANG}}/account/agency/statistics"><i class="glyph-icon flaticon-graphic" aria-hidden="true"></i><span>{{ trans('common.Statistics') }}</span></a></li>
@endif
<li @if(Request::segment(3) == 'bills') class="active" @endif><a href="{{SITE_LANG}}/account/bills"><i class="glyph-icon flaticon-document" aria-hidden="true"></i><span>{{ trans('common.Bills') }}</span></a></li>
